In [65]:
import pandas as pd
import numpy as np
import os
import sys
import csv

In [66]:
f= "F:\Xyz\SocialCops\DHIS (APRIL 15-MARCH 16)\data1.csv"

In [67]:
df = pd.read_csv(f)
df.head()

,Unnamed: 0,code,April_2015,May_2015,June_2015,July_2015,August_2015,September_2015,October_2015,November_2015,December_2015,Jan_2016,Feb_2016,March_2016,Total,Facility,Block,area,Name of facility
0,0,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,SC,Ramtek,Karwahi,Karwahi
1,1,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,BHIVPUR,Jawali,Jawali
2,2,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,BHIVPUR,Nand,Nand
3,3,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,BHIVPUR,Somnala,Somnala
4,4,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Hinga,Adegaon,Adegaon

In [68]:
df['code'].nunique()

250

In [69]:
df['mean']=df.mean(axis=1)
df.head()

,Unnamed: 0,code,April_2015,May_2015,June_2015,July_2015,August_2015,September_2015,October_2015,November_2015,December_2015,Jan_2016,Feb_2016,March_2016,Total,Facility,Block,area,Name of facility,mean
0,0,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,SC,Ramtek,Karwahi,Karwahi,0.000000
1,1,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,BHIVPUR,Jawali,Jawali,0.071429
2,2,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,BHIVPUR,Nand,Nand,0.142857
3,3,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,BHIVPUR,Somnala,Somnala,0.214286
4,4,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Hinga,Adegaon,Adegaon,0.285714

In [70]:
df.drop(df.columns[0], axis=1,inplace=True)  # df.columns is zero-based pd.Index

In [71]:
df.head()

,code,April_2015,May_2015,June_2015,July_2015,August_2015,September_2015,October_2015,November_2015,December_2015,Jan_2016,Feb_2016,March_2016,Total,Facility,Block,area,Name of facility,mean
0,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,SC,Ramtek,Karwahi,Karwahi,0.000000
1,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,BHIVPUR,Jawali,Jawali,0.071429
2,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,BHIVPUR,Nand,Nand,0.142857
3,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,BHIVPUR,Somnala,Somnala,0.214286
4,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Hinga,Adegaon,Adegaon,0.285714

In [72]:
df['mean']=df.mean(axis=1)

In [73]:
df.head()

,code,April_2015,May_2015,June_2015,July_2015,August_2015,September_2015,October_2015,November_2015,December_2015,Jan_2016,Feb_2016,March_2016,Total,Facility,Block,area,Name of facility,mean
0,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,SC,Ramtek,Karwahi,Karwahi,0.000000
1,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,BHIVPUR,Jawali,Jawali,0.005102
2,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,BHIVPUR,Nand,Nand,0.010204
3,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,BHIVPUR,Somnala,Somnala,0.015306
4,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Hinga,Adegaon,Adegaon,0.020408

In [74]:
df.loc[df['mean'].idxmax()]

code                14.12 |  Outpatient | 14.12.1 |  OPD attendanc...
April_2015                                                      16701
May_2015                                                        16526
June_2015                                                       15092
July_2015                                                       17878
August_2015                                                     18405
September_2015                                                  19643
October_2015                                                    19807
November_2015                                                   16843
December_2015                                                   19405
Jan_2016                                                        17620
Feb_2016                                                        18046
March_2016                                                      17742
Total                                                          213708
Facility                                                           WH
Block                                                          Nagpur
area                                                           Nagpur
Name of facility                                               Nagpur
mean                                                          33125.9
Name: 81431, dtype: object

In [75]:
test = df.sort_values(['mean'], ascending=[False])

In [76]:
test

,code,April_2015,May_2015,June_2015,July_2015,August_2015,September_2015,October_2015,November_2015,December_2015,Jan_2016,Feb_2016,March_2016,Total,Facility,Block,area,Name of facility,mean
81431,14.12 | Outpatient | 14.12.1 | OPD attendanc...,16701,16526,15092,17878,18405,19643,19807,16843,19405,17620,18046,17742,213708,WH,Nagpur,Nagpur,Nagpur,33125.872449
81054,14.11 | In-Patient Head Count at midnight | T...,12619,14701,12936,13473,15004,14318,16325,14357,13658,13070,13362,14405,168228,WH,Nagpur,Nagpur,Nagpur,26162.724490
81108,14.12 | Outpatient | 14.12.1 | OPD attendanc...,11067,9336,12625,13515,13232,14102,13255,9235,12024,10433,11745,11697,142266,RH,Kamptee,Kamptee,Kamptee,22189.224490
81107,14.12 | Outpatient | 14.12.1 | OPD attendanc...,6711,6794,7852,10924,9079,10845,9753,7031,9038,6564,8333,7625,100549,RH,Kamleshwar,Kamleshwar,Kamleshwar,15803.964286
81114,14.12 | Outpatient | 14.12.1 | OPD attendanc...,6049,6233,6750,8408,7548,9067,8922,6963,6471,5870,6825,7870,86976,RH,Ramtek,Ramtek,Ramtek,13726.500000
81115,14.12 | Outpatient | 14.12.1 | OPD attendanc...,5565,5628,3611,9306,7002,9925,9417,6210,7576,7247,7468,7923,86878,RH,Umred,Umred,Umred,13711.505102
81111,14.12 | Outpatient | 14.12.1 | OPD attendanc...,4400,4050,6732,6149,6186,8226,4860,4214,4830,5508,4913,4477,64545,RH,Narkhed,Narkhed,Narkhed,10293.168367
81106,14.12 | Outpatient | 14.12.1 | OPD attendanc...,4048,3425,4251,5765,5115,6400,6272,5517,5043,5166,5369,5092,61463,RH,Hinga,Hinga,Hinga,9821.408163
81110,14.12 | Outpatient | 14.12.1 | OPD attendanc...,4044,3783,3908,5637,4969,5615,5810,4100,4970,4605,5083,4640,57164,RH,Kuhi,Kuhi,Kuhi,9163.418367
81109,14.12 | Outpatient | 14.12.1 | OPD attendanc...,3997,2500,3622,5699,4987,5188,4939,4788,4259,5010,6003,5652,56644,RH,Katol,Katol,Katol,9083.821429
81105,14.12 | Outpatient | 14.12.1 | OPD attendanc...,4211,3912,3566,4939,3641,5562,6128,3641,4193,4159,4020,3498,51470,RH,BHIVPUR,BHIVPUR,BHIVPUR,8291.862245
52402,9.08 | Number of Condom pieces distributed | ...,2760,4900,5310,3720,5710,5010,3730,3910,4110,5880,3180,2570,50790,WH,Nagpur,Nagpur,Nagpur,8041.336735
81113,14.12 | Outpatient | 14.12.1 | OPD attendanc...,3461,3358,3586,5223,4018,5471,4981,3553,3973,3390,4250,3766,49030,RH,Ramtek(Devlapar),Ramtek(Devlapar),Ramtek(Devlapar),7918.433673
81088,14.12 | Outpatient | 14.12.1 | OPD attendanc...,3514,2892,3261,4339,3565,4896,3951,4319,4252,3689,4581,4236,47495,PHC,Parshivni,Kanhan,Kanhan,7683.357143
81112,14.12 | Outpatient | 14.12.1 | OPD attendanc...,3662,3778,3406,3935,4772,4528,5124,3452,3840,3641,3595,3534,47267,RH,Parshivni,Parshivni,Parshivni,7648.581633
81061,14.12 | Outpatient | 14.12.1 | OPD attendanc...,2710,2611,2768,4836,3967,4842,4245,3431,4493,4311,4511,3592,46317,PHC,Hinga,Raipur,Raipur,7502.913265
84070,M15 | Laboratory Testing | 15.1 | Laboratory...,3317,4483,4553,4325,3874,3971,3565,3584,3845,1951,2072,2134,41674,WH,Nagpur,Nagpur,Nagpur,6807.602041
81078,14.12 | Outpatient | 14.12.1 | OPD attendanc...,4412,2034,2520,3425,3004,3891,3660,2498,3008,3141,3103,3153,37849,PHC,Mouda,Mauda,Mauda,6206.877551
81097,14.12 | Outpatient | 14.12.1 | OPD attendanc...,2370,2180,2169,3210,2605,3657,3856,3109,3365,3202,3490,3197,36410,PHC,Saoner,Chicholi,Chicholi,5986.719388
81072,14.12 | Outpatient | 14.12.1 | OPD attendanc...,2069,2090,2299,3058,3078,4112,4135,2675,3010,2890,3367,3182,35965,PHC,Kuhi,Mandhal,Mandhal,5918.479592
81075,14.12 | Outpatient | 14.12.1 | OPD attendanc...,1953,1798,2153,2734,2819,3696,4060,4320,2352,2917,3152,3225,35179,PHC,Kuhi,Veltur,Veltur,5798.188776
81060,14.12 | Outpatient | 14.12.1 | OPD attendanc...,2902,2586,2179,2647,2603,3266,2867,2798,2654,2721,2978,2474,32675,PHC,Hinga,Kanholibara,Kanholibara,5414.846939
81070,14.12 | Outpatient | 14.12.1 | OPD attendanc...,2138,2090,2186,3406,3008,2065,3215,2665,2875,2741,2978,2637,32004,PHC,Katol,Kondhali,Kondhali,5312.193878
81057,14.12 | Outpatient | 14.12.1 | OPD attendanc...,3414,1756,2141,2746,2365,3835,3021,2043,2208,3831,2288,2326,31974,PHC,BHIVPUR,Nand,Nand,5307.535714
81100,14.12 | Outpatient | 14.12.1 | OPD attendanc...,2009,1752,1959,2827,2798,3644,3500,2666,2790,2415,2838,2725,31923,PHC,Saoner,Patansawangi,Patansawangi,5299.948980
81080,14.12 | Outpatient | 14.12.1 | OPD attendanc...,1947,2043,2236,3231,2710,3651,1905,2508,2958,2823,2867,2616,31495,PHC,Nagpur,Borkhedi,Borkhedi,5234.336735
81062,14.12 | Outpatient | 14.12.1 | OPD attendanc...,1940,1669,1882,3050,3161,3278,3316,2369,2360,2395,3598,2473,31491,PHC,Hinga,Takalghat,Takalghat,5233.632653
81082,14.12 | Outpatient | 14.12.1 | OPD attendanc...,2351,2176,2087,3344,3000,3999,2760,2281,2316,2306,1804,1684,30108,PHC,Narkhed,Jalalkheda,Jalalkheda,5022.051020
81065,14.12 | Outpatient | 14.12.1 | OPD attendanc...,2182,2151,1768,2998,2673,3371,2705,2137,2286,2452,2737,2272,29732,PHC,Kamleshwar,Mohapa,Mohapa,4964.413265
81099,14.12 | Outpatient | 14.12.1 | OPD attendanc...,2271,1703,2244,2761,2833,3112,3168,2099,2231,2144,2014,2697,29277,PHC,Saoner,Khapa,Khapa,4894.943878
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Narkhed,Mowad,Mowad,0.147959
28,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Narkhed,Mendhala,Mendhala,0.142857
27,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Narkhed,Jalalkheda,Jalalkheda,0.137755
26,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Nagpur,Vyahad,Vyahad,0.132653
25,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Nagpur,Borkhedi,Borkhedi,0.127551
24,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Mouda,Tarasa,Tarasa,0.122449
23,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Mouda,Mauda,Mauda,0.117347
22,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Mouda,Kondamendhi,Kondamendhi,0.112245
21,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Mouda,Khat,Khat,0.107143
20,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Kuhi,Veltur,Veltur,0.102041
19,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Kuhi,Titur,Titur,0.096939
18,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Kuhi,Salwa,Salwa,0.091837
17,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Kuhi,Mandhal,Mandhal,0.086735
16,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Katol,Yenava,Yenava,0.081633
15,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Katol,Kondhali,Kondhali,0.076531
14,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Katol,Kachrisawanga,Kachrisawanga,0.071429
13,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Kamptee,Gumthi,Gumthi,0.066327
12,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Kamptee,Gunthala,Gunthala,0.061224
11,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Kamleshwar,Tishti,Tishti,0.056122
10,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Kamleshwar,Mohapa,Mohapa,0.051020
9,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Kamleshwar,Gondkhairi,Gondkhairi,0.045918
8,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Kamleshwar,Dhapewada,Dhapewada,0.040816
7,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Hinga,Takalghat,Takalghat,0.035714
6,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Hinga,Raipur,Raipur,0.030612
5,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Hinga,Kanholibara,Kanholibara,0.025510
4,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,Hinga,Adegaon,Adegaon,0.020408
3,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,BHIVPUR,Somnala,Somnala,0.015306
2,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,BHIVPUR,Nand,Nand,0.010204
1,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,PHC,BHIVPUR,Jawali,Jawali,0.005102
0,17.3 | Infant/Child Deaths up to 5 years by c...,0,0,0,0,0,0,0,0,0,0,0,0,0,SC,Ramtek,Karwahi,Karwahi,0.000000